# docker-compose.yml
version: '3'
services:
  oebuild:
    build:
      context: ./
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    stdin_open: true
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /home/user/git_repos:/home/user/git_repos
      - /home/user:/home/user
    tty: true
    command: /bin/bash